### ISSUE TITLE
Redo build scripts

### ISSUE THREAD

**Issue by andrsd** [Open-Sn/openSn#1]
Tasks:

- [ ] remove references to chitech
- [ ] Use find LUA via `find_package`. this is available since cmake 3.18
- [ ] PETSc should be detected using `find_package`. this will need `FindPETSc.cmake`, but we can check PETSc version, etc.
- [ ] all supporting cmake modules are typically stored in `<ROOT>/cmake`, so move stuff there
- [ ] should use `target_link_libraries` and `target_include_directories` instead of `include_directories` and `link_directories` (these are global and really the include and linking stuff is always target specific).
- [ ] binaries should not be produced in the source tree

**Comment by ragusa** [comment]
I agree with these.
