### ISSUE TITLE
remove Kernels in the code

### ISSUE THREAD

**Issue by ragusa** [Open-Sn/opensn#116]
example: [modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.cc](https://github.com/Open-Sn/opensn/blob/fac8cc89d77d80520ff8eccbceba7e321cda7dfa/modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.cc#L53)

**Comment by andrsd** [comment]
Looking at the code, I am assuming you (@ragusa) want to remove the lists of pointers to member functions and go with good old function calls?

**Comment by wdhawkins** [comment]
Or... in the case where the kernel is only a few lines (which I'm guessing is most of them), put the code in-line. We may end of with small bits of duplicated code here and there, but the end result will be that the larger routines are cleaner and easier to understand.... IMHO.
