### ISSUE TITLE
lua module naming

### ISSUE THREAD

**Issue by ragusa** [Open-Sn/opensn#122]
Let's discuss before next week our ideas for lua module naming, such as `opensn.mesh.<function>.`
Same for solver, material, source?, ...

**EDIT:** After discussion on 21 FEB 2024, the following modules will be created:

### mesh

- [ ] Convert: `UnpartitionedMeshFromVTU`, `UnpartitionedMeshFromPVTU`, `UnpartitionedMeshFromEnsightGold`,
  `UnpartitionedMeshFromWavefrontOBJ`, `UnpartitionedMeshFromMshFormat`, `UnpartitionedMeshFromExodusII`,
  `ComputeLoadBalancing`, `SurfaceMeshCreate`, `SurfaceMeshImportFromOBJFile`,`SurfaceMeshImportFromTriangleFiles`
- [ ] Delete: `CreateEmptyUnpartitionedMesh`, `DestroyUnpartitionedMesh`, `MeshCreateUnpartitioned1DOrthoMesh`,
   `MeshCreateUnpartitioned2DOrthoMesh`, `MeshCreateUnpartitioned3DOrthoMesh`, `SurfaceMeshCheckCycles`,
   `SurfaceMeshExportToObj`, `SurfaceMeshExportPolyFile`

### lbs

- [ ] Convert: `LBSComputeBalance`, `LBSComputeLeakage`, `LBSSetPhiFromFieldFunction`, `LBSGetScalarFieldFunctionList`,
   `LBSWriteGroupsetAngularFlux`, `LBSReadGroupsetAngularFlux`, `LBSWriteFluxMoments`, `LBSCreateAndWriteSourceMoments`,
   `LBSReadFluxMomentsAndMakeSourceMoments`, `LBSReadSourceMoments`, `LBSReadFluxMoments`, `LBSComputeFissionRate`,
   `LBSInitializeMaterials`
- [ ] Delete: `AdjointSolverReadFluxMomentsToBuffer`, `AdjointSolverApplyFluxMomentBuffer`, 
   `AdjointSolverComputeInnerProduct`, `LBSSetProperty`, `LBSCreateGroupset`, `LBSCreateGroup`, `LBSGroupsetAddGroups`,
   `LBSGroupsetSetQuadrature`, `LBSGroupsetSetAngleAggregationType`, `LBSGroupsetSetAngleAggDiv`, 
   `LBSGroupsetSetGroupSubsets`, `LBSGroupsetSetIterativeMethod`, `LBSGroupsetSetResidualTolerance`, 
   `LBSGroupsetSetMaxIterations`, `LBSGroupsetSetGMRESRestartIntvl`, `LBSGroupsetSetEnableSweepLog`, 
   `LBSGroupsetSetWGDSA`, `LBSGroupsetSetTGDSA`, `LBSAddPointSource`, `LBSClearPointSources`
- [ ] Review: `AdjointSolverExportImportanceMapBinary`, `AdjointSolverMakeExpRepFromP1Moments`

### diffusion

- [ ] Convert: `CFEMDiffusionSolverCreate`, `CFEMDiffusionSetBCProperty`, `DFEMDiffusionSolverCreate`, 
   `DFEMDiffusionSetBCProperty`, `FVDiffusionSolverCreate`, `FVDiffusionSetBCProperty`, `CFEMMGDiffusionSolverCreate`,
   `CFEMMGDiffusionSetBCProperty`

### prk

- [ ] Convert: `PRKGetParam`, `PRKSetParam`

### opensn

Top level module: `Exit`, `ProgramTime`, `Sleep`, `MPIBarrier`

### log

- [ ] Convert: `LogSetVerbosity`, `Log`, `LogProcessEvent`, `LogPrintTimingGraph`

### aquad

- [ ] Convert: `OptimizeAngularQuadratureForPolarSymmetry`, `CreateCustomAngularQuadrature`, 
   `CreateCylindricalProductQuadrature`, `CreateSphericalProductQuadrature`, `CreateProductQuadrature`, 
   `CreateSLDFESQAngularQuadrature`, `GetProductQuadrature`, `Legendre`, `LegendreDerivative`, `Ylm`, 
   `LocallyRefineSLDFESQAngularQuadrature`
- [ ] Delete: `PrintToPythonSLDFESQAngularQuadrature`
- [ ] Revisit: `CreateLineQuadrature`

### fieldfunc

- [ ] Convert: `FFInterpolationCreate`, `FFInterpolationExportPython`, `FFInterpolationGetValue`, 
   `FFInterpolationInitialize`, `FFInterpolationExecute`, `FFInterpolationSetProperty`, `FieldOperationExecute`,
   `ExportFieldFunctionToVTK`, `ExportMultiFieldFunctionToVTK`, `GetFieldFunctionHandleByName`

### solver

- [ ] Convert: `SolverCreate`, `SolverInitialize`, `SolverExecute`, `SolverStep`, `SolverAdvance`, `SolverGetName`,
   `SolverGetInfo`, `SolverSetProperties`
- [ ] Revisit: `SolverSetBasicOption`, `SolverGetFieldFunctionList`

### mat
 
- [ ] Convert: `PhysicsAddMaterial`, `PhysicsMaterialAddProperty`, `PhysicsMaterialSetProperty`, `PhysicsMaterialGetProperty`

### logvol

- [ ] Convert: `LogicalVolumeCreate`, `LogicalVolumePointSense`

### xs

- [ ] Convert: `PhysicsTransportXSCreate`, `PhysicsTransportXSSet`, `PhysicsTransportXSMakeCombined`, 
   `PhysicsTransportXSSetCombined`, `PhysicsTransportXSGet`, `PhysicsTransportXSExportToOpenSnFormat`

## Other tasks

- [ ] Delete: `FunctionDimAToDimBEvaluate`

**Comment by andrsd** [comment]
I propose:
- `opensn.lbs.<API>` for everything related to linear Boltzmann solvers

For diffusion solvers, may be?
- `opensn.cdiffusion`
- `opensn.ddiffusion`
- `opensn.mgdiffusion`

Should there be underscore, like `mg_diffusion`? Is that too long? Maybe using just {c|d} is too short, so people may misread/mistype. Comments?

For the point reactor kinetics:
- `opensn.prk.<API>`

**Comment by andrsd** [comment]
Another thought, should there by just `diffusion` module that would have cfem, dfem, mg in it? Would that make sense?

**Comment by zhardy-lanl** [comment]
> Another thought, should there by just `diffusion` module that would have cfem, dfem, mg in it? Would that make sense?

I like this idea a bit better... however, `mg` (multi-group) does not belong in the same category as `cfem` and `dfem`. In other words, you can have a `cfem` and `dfem` `mgdiffusion` solver (whether that is implemented or not, I am unsure). This brings on a more nuanced conversation about how we should organize our diffusion solvers

**Comment by ragusa** [comment]
all the diffusion solvers (except the oldest one, which we deleted), are mine. I used the excuse to write them to learn chi-tech. The dfem solver was extremely useful, as I found bugs in the dfem implementation that made the code not 2nd order. Then, for that point, it was easy to do multigroup and I wanted to check the two-grid process. They are legacy, but less old than the old diffusion solver. The only usefull would be (1) if someone wants to do a diffusion solve and compare transport against it or (2) to actually provide an initial guess to the transport solver. I know they are unfinished (do not have enough options) and I would like to finish them at some point but this is not a priority for me now.

**Comment by ragusa** [comment]
Attaching the list of Lua functions that are registered either as is or through a namespace

[RegisterLuaFunctionNamespace.txt](https://github.com/Open-Sn/opensn/files/14350861/RegisterLuaFunctionNamespace.txt)
[RegistraLuaFunctionAsIs.txt](https://github.com/Open-Sn/opensn/files/14350862/RegistraLuaFunctionAsIs.txt)
