### ISSUE TITLE
mesh refactoring

### ISSUE THREAD

**Issue by ragusa** [Open-Sn/opensn#17]
Let's address mesh refactoring (for detailled discussions, please go to the appropriate slack channel).
- [x] `VolumeMesher` has to go but some lua functions rely on methods from `VolumeMesher`: `chiVolumeMesherSetProperty`, `chiVolumeMesherSetupOrthogonalBoundaries`, `chiVolumeMesherSetMatIDToAll`. The methods we need to keep should go to `MeshModifiers`
- [x] `UnpartitionedMesh`: keep but some lua functions are unknown to me and are not called: `chiUnpartitionedMeshUploadVertex`, `chiUnpartitionedMeshUploadCell`, `chiUnpartitionedMeshFinalizeEmpty` so I think these can go
- [x] `SurfaceMesher`: I couldn't see any test that used any of the 3 lua functions from this so it can go.
- [x] `mesh_cutting `should go (we determined that cutting for KBA is no longer something we want to do)
- [x] `domain_decomposition `should go (looks old and unused)
- [x] I do not think `SurfaceMesh `is of any use. IT is, of course, referenced in many places. Unless it is useful for setting boundaryID using LV (if boundaryID cannot be set with LV), I'd say remove. I'd like for @zachhardy to confirm

**Comment by zhardy-lanl** [comment]
@ragusa I have never used `SurfaceMesh`. No issue removing it on my end.

**Comment by andrsd** [comment]
I identified what `UnpartitionedMeshUploadVertex`, `UnpartitionedMeshUploadCell`, and `UnpartitionedMeshFinalizeEmpty` do. They allow users to create meshes directly from the lua file, i.e. `UnpartitionedMeshUploadVertex` is used to create vertices and `UnpartitionedMeshUploadCell` is used to build cells.

So question. Do you want to keep this functionality or just remove it? They are not being tested by anything.

**Comment by ragusa** [comment]
We want to limit users from creating meshes from opensn directly. I think they need to either be satisfied with ortho grids and our extrusion options. Everything else should be done in real mesh generators. So, I am fine killing the above functionality.

**Comment by ragusa** [comment]
`SurfaceMesh` is used when create a logical volume with a skin mesh. so we are keeping `SurfaceMesh`. See PR #135

**Comment by ragusa** [comment]
SurfaceMesher was deleted in PR #89

**Comment by andrsd** [comment]
>We want to limit users from creating meshes from opensn directly. I think they need to either be satisfied with ortho grids and our extrusion options. Everything else should be done in real mesh generators. So, I am fine killing the above functionality.

I agree, this feels a little bit too much fine grained. And we should not really on the fact that user will do the right thing (they never do :-D). I will send  a PR removing that API shortly.

**Comment by andrsd** [comment]
This is no completed
