### ISSUE TITLE
Improve support for command-line options

### ISSUE THREAD

**Issue by wdhawkins** [Open-Sn/opensn#197]
Our current support for command-line options is ad-hoc and a bit fragile. We should at the very least be using `getopt_long` and preferably something like CLI11.

**Comment by andrsd** [comment]
I have been using [cxxopts](https://github.com/jarro2783/cxxopts). It is basically just one header file that would go into `external/cxxopts`. 

I was using [TCLAP](https://tclap.sourceforge.net/) before, but I like `cxxopts` a little bit better - mostly because it is just a single header file.

**Comment by andrsd** [comment]
I agree that the command line parsing code should be handled by a modern library.

**Comment by wdhawkins** [comment]
I'll try to put in a couple hours this week... it should be pretty easy to clean up.

**Comment by wdhawkins** [comment]
Closed with #204.
