### ISSUE TITLE
ghost cells identification at high-core counts

### ISSUE THREAD

**Issue by ragusa** [Open-Sn/opensn#20]
ghost cells identification at high-core counts is taking too long.

**Comment by andrsd** [comment]
This should be labeled as `bug` rather than `enhancement`, since the code does not behave as expected.

**Comment by ragusa** [comment]
I think @wdhawkins  will compile data for this Friday. It’d be good to add a couple of screenshot of figures or tables here when we have them. So we can also see improvement. I will let Daryl switch to a bug label at that time.
