### ISSUE TITLE
Command line arguments inconsistencies

### ISSUE THREAD

**Issue by andrsd** [Open-Sn/opensn#213]
There are currently 2 modes of operation: 

1. Interactive mode

   Users do:
   ```
   ./opensn [lua-arg]
   ```

2. Batch mode

   Users do:
   ```
   ./opensn file-name [lua-arg]
   ```

We treat `file-name` and `lua-arg` as positional arguments, which means they have to be supplied. But, as you can see, both are actually **optional** arguments:
- If `file-name` is specified, we run batch mode. If not, we run in interactive mode.
- `lua-arg`s are just checked if they include `=` and if so they are added to the lua processing buffer, but in general this can actually be any lua command.

## Proposed change

This can be changed to:
1. Using `-i` option for an input file, this would be setting the batch/interactive mode
2. Using `-l` (or whatever else) for the lua arguments - could be supplied multiple times, like so `-l var1=100 -l var2=102`

**Comment by ragusa** [comment]
I would be fine with this. This only annoying thing in what you are proposing is that one has to repear `-l` in front of each lua argument. Can we have `-l` once ?

**Comment by andrsd** [comment]
We can do `-l var1=100,var2=200` instead. The problem with suppling multiple values (like for the lua params) is that you need a second delimiter to separate individual elements...

**Comment by wdhawkins** [comment]
I very much like this idea. I hate positional arguments... to many corner cases to deal with. I can add a patch for this in 10 minutes.  For Lua expressions, using quotes will allow you to have multiple expressions for a single -l ( it also prevents you from having to escape a bunch of characters so that the shell doesn't try to interpret them):

lua/opensn -i myinput -l "x=2 print(x) y=x*x print(y)"

would work.

**Comment by andrsd** [comment]
Good point about escaping characters and using `"` for longer lua code :+1:. That should be the way to go. I can see that the comma-separated arguments could easily fail on mode complex lua statements.

**Comment by ragusa** [comment]
Great. Looks like we have a way forward.
