### ISSUE TITLE
Assertion in `mpicpp-lite/impl/Communicator.h`

### ISSUE THREAD

**Issue by wdhawkins** [Open-Sn/opensn#231]
In `debug` builds, we trigger the following assertion for some test problems:
```
opensn-test: .../opensn/external/mpicpp-lite/impl/Communicator.h:519:
void mpicpp_lite::Communicator::send(int, int, const T *, int) const [T = int]:
Assertion `values != nullptr' failed.
```

The function signature looks like:
```
template <typename T>
void
Communicator::send(int dest, int tag, const T * values, int n) const
```

I believe a value of `nullptr` is valid here if `n == 0` (see 3.2.2 of the MPI standard). We probably just need to update the assert.

**Comment by andrsd** [comment]
I patched `mpicpp-lite`, see [PR](https://github.com/andrsd/mpicpp-lite/pull/26/files). I will update the lib in opensn momentarily.
