### ISSUE TITLE
openmc tests are failing with hdf-1.12

### ISSUE THREAD

**Issue by andrsd** [Open-Sn/opensn#235]
With HDF-1.12, I see this:
```
[ 4] modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs.lua.......................Failed 0.0s
[ 4] modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs_cset.lua..................Failed 0.0s
```

The error is:
```
**!**ERROR**!** Could not find dataset set1/294K in uo2.h5
```

Looking at the file:
```
$ h5dump -n uo2.h5
HDF5 "uo2.h5" {
FILE_CONTENTS {
 group      /
 group      /set1
 group      /set1/294K
 dataset    /set1/294K/absorption
 dataset    /set1/294K/chi
 dataset    /set1/294K/fission
 dataset    /set1/294K/inverse-velocity
 dataset    /set1/294K/nu-fission
 dataset    /set1/294K/prompt-nu-fission
 group      /set1/294K/scatter_data
 dataset    /set1/294K/scatter_data/g_max
 dataset    /set1/294K/scatter_data/g_min
 dataset    /set1/294K/scatter_data/multiplicity_matrix
 dataset    /set1/294K/scatter_data/scatter_matrix
 dataset    /set1/294K/total
 group      /set1/kTs
 dataset    /set1/kTs/294K
 }
}
```

So, 1.12 sees datasets under _group_ called `/set1/294K`. I am wondering if 1.14 (which is build by the configure_dependencies) changed some behavior...

**Comment by andrsd** [comment]
I should be able to investigate this maybe this afternoon...

**Comment by andrsd** [comment]
I am not marking this as a bug, since this may be correct behavior with 1.14. But, it may be worth to see if we can support older hdf5 versions easily...

**Comment by wdhawkins** [comment]
That's interesting... and little shocking. I wouldn't expect such a drastic change in behavior. I have today set aside to work on a presentation, so I'll have time off and on.  Let me start by installing 1.12 and replicating the problem. If 1.14 did introduce a breaking change, it should be easy to test both options without having to worry about what version of hdf wrote the file and what version is being used to read it.

**Comment by wdhawkins** [comment]
Both.  The jupyter notebook just calls the OpenMC python wrappers to run OpenMC and write the library... so, ultimately, the hdf file was created by OpenMC.

**Comment by wdhawkins** [comment]
After looking more closely at your `h5dump`, I don't see anything wrong with it.  I'll have to do some testing to see what's  really going on.

**Comment by wdhawkins** [comment]
With a fresh install of 1.12.3 from source using `configure_dependencies.py`, I'm able to run both of the openmc tests without any problems. Regarding the c/c++ hdf interfaces - I can easily convert `hdf_utils` to only use the hdf c interface if that makes things easier.

**Comment by andrsd** [comment]
This could be caused by something on my machine. I have VTK built with HDF5 as well, and it looks like that library is dynamically loaded instead of the expected one from my $CONDA_PREFIX. I enabled HDF5 error reporting and I see this:
```
HDF5-DIAG: Error detected in HDF5 (1.13.1) thread 0:
  #000: /path/conda-bld/vtk_1704845469352/work/ThirdParty/hdf5/vtkhdf5/src/H5L.c line 1238 in vtkhdf5_H5Lexists(): unable to synchronously check link existence
    major: Links
    minor: Can't get value
  #001: /path/conda-bld/vtk_1704845469352/work/ThirdParty/hdf5/vtkhdf5/src/H5L.c line 1200 in H5L__exists_api_common(): can't set object access arguments
    major: Links
    minor: Can't set value
  #002: /path/conda-bld/vtk_1704845469352/work/ThirdParty/hdf5/vtkhdf5/src/H5VLint.c line 2744 in vtkhdf5_H5VL_setup_name_args(): invalid location identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
  #003: /path/conda-bld/vtk_1704845469352/work/ThirdParty/hdf5/vtkhdf5/src/H5VLint.c line 1779 in vtkhdf5_H5VL_vol_object(): invalid identifier
    major: Invalid arguments to routine
    minor: Inappropriate type
```

I even tried to open the existing group `/set1` via `H5Gopen` and that is failing too. So, I will try to rebuild my VTK and see what happens... Looks like I am experiencing dependency hell :-(

**Comment by andrsd** [comment]
Finally, I figured this out. In the end and luckily, all that was needed was to build VTK with `-DVTK_MODULE_USE_EXTERNAL_VTK_hdf5=ON`. This way VTK does not use its bundled HDF5 and uses the installed one.

However there is one extra problem. The C++ component of HDF5 is not being linked. Had to add `${HDF5_CXX_LIBRARIES}` into `target_link_libraries(libopensn ...`. With that I get a clean build and clean tests. I will send a patch for the missing link line soon. I will test this also in conda on linux, so far I only worked on macOS...

**Comment by wdhawkins** [comment]
> One more comment. The way we build VTK, the build process builds HDF5 and deploys that. Then, there are 2 instances of HDF5 linked to the binary/libs, so that creates a problem. But, it only manifests sometimes?

I'll look at modifying `configure_dependencies.py` to have `VTK` use an external HDF5 installation. If everything works correctly, I'll also update the installation instructions.
