### ISSUE TITLE
PETSc Graph Partitioner Bug

### ISSUE THREAD

**Issue by rodriguez-jay** [Open-Sn/opensn#260]
When using the PETScGraphPartitioner I am getting some processors with odd cell coverage, image below;
![ParIssue](https://github.com/Open-Sn/opensn/assets/35831702/87846bc4-8c08-4ddc-a868-7e0af119de5d)

I am importing a mesh from gmsh and noticed some sluggish convergence which brought me to look at the partitioning. I've attached a tar of my working directory for this issue. 
[PGPIssue.tar.gz](https://github.com/Open-Sn/opensn/files/15266857/PGPIssue.tar.gz)

If it helps, I have OpenSn built with gcc-12, but I recall seeing this issue as well with gcc-13 on cluster.

**Comment by wdhawkins** [comment]
Just out of curiosity, what do metis or scotch do?

**Comment by rodriguez-jay** [comment]
I am not too sure how to check that. How would I go about looking into that?

**Comment by rodriguez-jay** [comment]
I have resolved the bug, it has nothing to do with OpenSn. I had issues with physical groups in Gmsh;
![Screenshot from 2024-05-10 23-30-26](https://github.com/Open-Sn/opensn/assets/35831702/267d2702-4599-4044-b16a-80e41ef98b56)
![Screenshot from 2024-05-10 23-31-01](https://github.com/Open-Sn/opensn/assets/35831702/db017968-6dda-4c31-9607-fb0694a4f9b0)

I started using mesh fields and I had miss handled the order of things.
