### ISSUE TITLE
Organize field functions and related utilities

### ISSUE THREAD

**Issue by zhardy-lanl** [Open-Sn/opensn#29]
Field functions are spread across three directories: 1) `physics/field_functions`, 2) `physics/field_operations`, and 3) `mesh/field_function_interpolation`. These should likely be organized in one place. My proposal is 

- `field_functions`
    - `operations`
    - `interpolation`
    - `.h` and `.cc` files defining field functions

It may make sense to move `field_function` out of `physics` as well.

**Comment by andrsd** [comment]
Would it make sense to you guys to move `field_functions` under `math`?

**Comment by ragusa** [comment]
I think field function  should be a thing on its own. It is a fairly large fraction of the code and is actually what we use for post-processing and should be used for coupling. I will let others chime in but I feel like I prefer it as in a standalone directory

**Comment by andrsd** [comment]
So at the same level as `math`, or `physics`?

**Comment by zhardy-lanl** [comment]
I agree with @ragusa. It is not quite physics, not quite math, and has many different use cases. I say it make it be on the same level as `math` and `physics`.
