### ISSUE TITLE
Code style / Naming conventions

### ISSUE THREAD

**Issue by andrsd** [Open-Sn/opensn#3]
This issue is here to decide on the coding style.  Currently the code is a mix of different styles, but the code should really just use one style.

```
directory_name/header_file_name.h
directory_name/source_file_name.cc
```

```
#define MacroDefinition(parameter)

namespace out_namespace {

enum OurEnumType {
  ENUM_VALUE_1,
  ENUM_VALUE_2,
  ...
}

class ThisIsAClassName {
public:
   int public_member_var;
protected:
   int my_member_variable_;
   double another_member_variable_;

   void MyCoolMemberFunction();
   void MemberFunctionWithAnArgument(int argument_name);
};

struct ThisIsAStructName {
   int public_member_var;

   void MyCoolMemberFunction();
   void MemberFunctionWithAnArgument(int argument_name);

protected:
   int my_member_variable_;
   double another_member_variable_;
};

}
```

Command line parameters:
```
--cmd-line-switch1 --cmd-line-switch2
```

**Comment by andrsd** [comment]
Free free to comment on stuff that should be kept or changed.

**Comment by ragusa** [comment]
I am ok with snake case and pascal case as you have shown.

**Comment by wdhawkins** [comment]
I'm happy with this style. No changes from me. I would like to talk a bit about comments.  I'm not a fan of the current comment style (which typically includes a long line of "=").  Thoughts?

**Comment by andrsd** [comment]
I saw 2 kinds of this style:
1. something like this `// ============` that was in between functions. Those need to go - they are useless.
2. something like `// ========= comment`. This needs to be changed into `// comment`.

**Comment by wdhawkins** [comment]
> I saw 2 kinds of this style:
> 
>     1. something like this `// ============` that was in between functions. Those need to go - they are useless.
> 
>     2. something like `// ========= comment`. This needs to be changed into `// comment`.

Yes!  Perfect. I'm fine with `// ` or `/*  */` syntax, but prefer `// `.

**Comment by andrsd** [comment]
I also prefer `//`. I think the `/* */` works well only for doxygen-style comments, but not in code...

**Comment by zhardy-lanl** [comment]
There is also a mixture of different getter function names that should probably be standardized. Take for example
```
class MyClass
{
public:
  // Option 1
  Type Member() { return member_; }

  // Option 2
  // Type GetMember() { return member_; }
  
private:
  Type member_;
};
```

**Comment by andrsd** [comment]
@zhardy-lanl What do you propose for a setter? `void  SetMember(Type value)` or `void Member(Type value)`?

**Comment by zhardy-lanl** [comment]
I think I prefer `void SetMember(Type value)`. I also fully recognize the inconsistency in omitting `Get` but using `Set`. 

Assume the instance `MyClass obj`. The line of code `auto value = obj.Member();` reads as a getter function because of the `=`. To me, there is no ambiguity that that is a getter function. The "consistent" counterpart `obj.Member(Type(...));` on the other hand, does not naturally read as a setter routine (no `=`), while `obj.SetMember(Type(...))`, does (`Set` implies `=`).

**Comment by andrsd** [comment]
`Type Member()` for getter and `void SetMember(Type value)` for setter is the convention used in Qt. I have no problem with it...

**Comment by ragusa** [comment]
can someone give me an example with a getter for a pointer (or a pointer to a pointer). just want to make sure it is clear to me that not using Get is not confusing. Just a thought (as I am already in favor of what is in the comment right above)

**Comment by zhardy-lanl** [comment]
@ragusa I would propose returning all members in the type they are stored. In other words, I would change the getter paradigm used only some of the time from

```
class LBSSolver
{
public:
    const MeshContinuum& Grid() { return *grid_ptr_; }
protected:
    shared_ptr<MeshContinuum> grid_ptr_;
};
```
to 
```
class LBSSolver
{
public:
   const  shared_ptr<MeshContinuum>& Grid() { return grid_; }
protected:
    shared_ptr<MeshContinuum> grid_;
};
```
I have never been a fan of the `_ptr` member suffix or the `Ptr` method suffix.
