### ISSUE TITLE
possibly many errors in input files in the regression suite

### ISSUE THREAD

**Issue by ragusa** [Open-Sn/opensn#310]
if I run the script `run_tests`, all tests pass. 

However, if I use the binary from `build\lua\opensn` and try to run  it with the file `test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance.lua`, I get several errors.

1. the first error was at line 71. In the groupset block, the angular quadrature name is `pquad0` while it was created as `pquad` in line 63. The binary `build\lua\opensn` bombs while the regression suite passes that test.
2. the second error occurred at the post-processing stage, line 130 where the field function entry indexed as `160` is passed. The problem is that this test is a 1-group problem so there are no field functions with an index equal to 160. In line 117, you can see that the other post-processing step uses index `1`. Again, the binary `build\lua\opensn` bombs while the regression suite passes that test.

So, why is the standard binary catching those errors and not the binary that is run by the regression suite? (I suppose the regression suite uses a different binary exe.) 

And how many more such mistakes do we have in the regression suite? I just happened to try one input file, at random !!

**Comment by wdhawkins** [comment]
I’ve never been a fan of having two executables. I’m not sure why one behaves differently from the other. I’ll look at this tonight. To start, I can fix all the mistakes in the inputs and make sure everything passes.

**Comment by wdhawkins** [comment]
I think a lot of the post processing stuff is guarded behind a master_export variable that defaults to false or nil during the running of the regression tests.

**Comment by andrsd** [comment]
The test binary links in the `opensnlua` (so does `opensn`) and the test library (which contains some unit tests). That's why there are 2 binaries...

**Comment by ragusa** [comment]
the post-processing that bombed is NOT behind master_export (that's only for vtk and python). So that's likely not why the test passes with the testbinary exec.

**Comment by ragusa** [comment]
even stranger, I had forgotten to remove those lines when I did PR#308
```
--############################################### Slice plot
slice2 = fieldfunc.FFInterpolationCreate(SLICE)
fieldfunc.SetProperty(slice2, SLICE_POINT, { x = 0.0, y = 0.0, z = 0.025 })
fieldfunc.SetProperty(slice2, ADD_FIELDFUNCTION, fflist[1])

fieldfunc.Initialize(slice2)
fieldfunc.Execute(slice2)
```
and the test passes even though SLICE is no longer a valid option

**Comment by andrsd** [comment]
It does not seem that `transport_2d_1_poly_balance.lua` is being executed by the run_test script. It is not included in the `tests.json`.

**Comment by ragusa** [comment]
ok. that would ake sense. it is still a bit weird that input files are in test and are not used.

**Comment by ragusa** [comment]
I write a short script: 4 or 5 culprits

```
Subdirectory: ./modules/dfem_diffusion
Lua files missing in tests.json: ['d_diffusion_2d_3c_l2_error_mms.lua']
Extra files in tests.json not found as .lua: []

Subdirectory: ./modules/linear_boltzmann_solvers/transport_keigen/c5g7
Lua files missing in tests.json: ['c5g7.lua']
Extra files in tests.json not found as .lua: []

Subdirectory: ./modules/linear_boltzmann_solvers/transport_steady
Lua files missing in tests.json: ['transport_2d_1_poly_balance.lua', 'transport_1d_4_dsa_ortho_inf.lua', 'transport_2d_1_poly_balance_mg.lua']
Extra files in tests.json not found as .lua: []
```

**Comment by wdhawkins** [comment]
The missing `c5g7.lua` is ok. This file not being in `tests.json` is a side effect of the test script not being able to recognize a filename + lua parameters as a unique test. If you look in that directory, you'll see that we have separate files for each different solution algorithm: `c5g7_jfnk.lua`, `c5g7_pi.lua`, `c5g7_pi_smm.lua`, etc.

**Comment by ragusa** [comment]
@wdhawkins I have a PR pending but the QA does not want to run the regression suite. It has been queued for 30+ minutes now. Is the machine down?

**Comment by andrsd** [comment]
Nightly builds are running ATM, so after that is done, your PR should get tested...

**Comment by andrsd** [comment]
Sorry, they are **scheduled**, not running...
