### ISSUE TITLE
consistency in LuaCheckArgs<size_t>(L, fname)

### ISSUE THREAD

**Issue by ragusa** [Open-Sn/opensn#314]
should it be 
`LuaCheckArgs<size_t>(L, fname)` 
or
`LuaCheckArgs<int>(L, fname)` 
?

**Comment by andrsd** [comment]
If your first argument is supposed to be of type `size_t`, then it is `LuaCheckArgs<size_t>(L, fname)`. If your first argument is supposed to be `int`, then it is `LuaCheckArgs<int>(L, fname)`. This is not either-or situation.

For example, if your lua C function takes `int`, `string` and `float`, then your C++ code would do `LuaCheckArgs<int, std::string, float>(L, fname)`. Then, this call checks that 3 arguments were supplied and they are of the desired types.

**Comment by ragusa** [comment]
got it.
