### ISSUE TITLE
groupsets issue with k-eigenvalue simulations

### ISSUE THREAD

**Issue by ragusa** [Open-Sn/opensn#321]
I run a problem with 172g XS obtained from OpenMC. I do not get the same answers when using a single group set versus more group sets.
GS-n: n groupsets
MPI-r: r ranks
```
GS-1, MPI-1  : keff = 1.179888
GS-1, MPI-12: keff = 1.179893

GS-3, MPI-1. : keff = 1.022954
GS-3, MPI-12: keff = 1.714134
```

With more mesh cells and more directions, the symptoms are identical. I am attaching the smaller mesh size problem. It runs quickly.
[gs.tar.gz](https://github.com/user-attachments/files/16041650/gs.tar.gz)

**Comment by ragusa** [comment]
I have looked in the regression suite, we do not have a single test case that uses more than 1 group set.

**Comment by wdhawkins** [comment]
Ugh... this strikes me as a difficult one.  To start with, I can easily get a segfault with different groupset structures. I'll get that fixed first. Hopefully it's the root cause of all of our problems. We'll see.
