### ISSUE TITLE
Outdated Installation Tutorial

### ISSUE THREAD

**Issue by quincy-huhn98** [Open-Sn/opensn#365]
I am attempting to install and compile OpenSn and was following the quick install guide. In the quick install guide the Easy Install on Linux Machines and Easy Install on MacOS sections both reference a script that seems to have been removed by PR #337.

**Comment by andrsd** [comment]
The script is now in [`tools/`](https://github.com/Open-Sn/opensn/tree/main/tools).

Thanks for reporting this!

**Comment by andrsd** [comment]
Closed by #365
