### ISSUE TITLE
Implicit integer conversions and float divide-by-zero issues

### ISSUE THREAD

**Issue by wdhawkins** [Open-Sn/opensn#378]
We have a handful of implicit integer conversions and floating point divide-by-zero issues that need to be fixed. They are easy to find with the following compile line:

`cmake -DCMAKE_CXX_FLAGS="-fsanitize=float-divide-by-zero,implicit-conversion -fno-sanitize-recover" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=float-divide-by-zero,implicit-conversion -fno-sanitize-recover" ..`

and running the test suite.

**Comment by andrsd** [comment]
Now, that #406 is merged, I think this can be closed. Thoughts?
