### ISSUE TITLE
AAH for the one-sweep methods on the C5G7 benchmark

### ISSUE THREAD

**Issue by zhardy-lanl** [Open-Sn/opensn#428]
The AAH sweeper does not currently work with one-sweep methods on the C5G7 benchmark. The reason for this is not currently known. This issue dates back to ChiTech.

**Comment by ragusa** [comment]
Did it work before PR#403?

**Comment by zhardy-lanl** [comment]
> Did it work before PR #403?

When the methods that should be doing one sweep did multiple sweeps, I believe that it did work.

**Comment by wdhawkins** [comment]
> > Did it work before PR #403?
> 
> When the methods that should be doing one sweep did multiple sweeps, I believe that it did work.

Ahhh.... yes. I believe this. I can imagine some acceleration schemes will have issues with single-sweep AAH when we have lagged angular fluxes. I think the one-sweep solution is just too noisy for acceleration to be effective (or even work).  I think the only fixes for this are multiple sweeps or CBC.

**Comment by ragusa** [comment]
are there lagged angular flux in any c5g7 mesh?

**Comment by wdhawkins** [comment]
> * Did it work before PR [Extra Sweeps Fix #403](https://github.com/Open-Sn/opensn/pull/403)?
> 
>     * is the issue present for vanilla PI or only for accelerated PI schemes?

Vanilla PI, SMM, and JFNK are unaffected. Just SCDSA. I say SMM is unaffected, but I didn't look close enough to judge if it's as effective with one sweep as it was with multiple sweeps. Based on timings, I would say it's unaffected.

**Comment by wdhawkins** [comment]
> are there lagged angular fluxes in any c5g7 mesh?

Yes. According to the code, 0.86% of the angular unknowns are lagged. That's not much, but I it looks like it's enough to cause issues. I don't know that anyone has ever looked at that metric in relation to the stability of acceleration schemes, etc.

**Comment by ragusa** [comment]
If we have goods to state that SMM with DG is as effective as SCDSA (have the goods = give me some time to run a few CASL cases), I would then say we get rid of SCDSA. I am in a weed whacking mood.

**Comment by wdhawkins** [comment]
> > are there lagged angular fluxes in any c5g7 mesh?
> 
> Yes. According to the code, 0.86% of the angular unknowns are lagged. That's not much, but I it looks like it's enough to cause issues. I don't know that anyone has ever looked at that metric in relation to the stability of acceleration schemes, etc.

I should clarify that these lagged angular unknowns are not inherent in the mesh itself. They are the result of the partitioning.

**Comment by ragusa** [comment]
> > are there lagged angular fluxes in any c5g7 mesh?
> 
> Yes. According to the code, 0.86% of the angular unknowns are lagged. That's not much, but I it looks like it's enough to cause issues. I don't know that anyone has ever looked at that metric in relation to the stability of acceleration schemes, etc.

I am surprized. Which mesh, the coarse or the fine? I'd like to put it through networkX and see if it finds those cycles.

**Comment by zhardy-lanl** [comment]
> If we have goods to state that SMM with DG is as effective as SCDSA (have the goods = give me some time to run a few CASL cases), I would then say we get rid of SCDSA. I am in a weed whacking mood.

I wouldn't get rid of SCDSA until we refactor the eigenvalue acceleration methods. We can prefer to use SMM, but I don't think that means we should get rid of everything else. Particularly when journal publications show results with that method.

**Comment by wdhawkins** [comment]
If I run the SCDSA version with only 4 ranks instead of 32, it will converge. IIRC, the lagged angular flux percentage goes from 0.86% to 0.2%.

**Comment by zhardy-lanl** [comment]
> If I run the SCDSA version with only 4 ranks instead of 32, it will converge. IIRC, the lagged angular flux percentage goes from 0.86% to 0.2%.

This likely explains why the one other SCDSA works fine while the C5G7 test breaks. It all depends on the fraction of lagged angular fluxes. We could force SCDSA (and maybe SMM) to use CBC, or we could print a warning if the lagged angular flux percentage exceeds a certain percentage when using SCDSA (and maybe SMM) with one sweep.

**Comment by wdhawkins** [comment]
> > If I run the SCDSA version with only 4 ranks instead of 32, it will converge. IIRC, the lagged angular flux percentage goes from 0.86% to 0.2%.
> 
> This likely explains why the one other SCDSA works fine while the C5G7 test breaks. It all depends on the fraction of lagged angular fluxes. We could force SCDSA (and maybe SMM) to use CBC, or we could print a warning if the lagged angular flux percentage exceeds a certain percentage when using SCDSA (and maybe SMM) with one sweep.

Yes, I think my next side project will be working on our iteration reporting. I'll add a warning about lagged angular fluxes and acceleration. I think it's likely that the larger the fraction of lagged angular fluxes you have, the more sweeps you need to get the noise down. And it may be that you only need to do the extra sweeps at the beginning of the problem and can then drop down to one sweep. This will likely take a bit of work to develop some idea of how all of these processes are related.

**Comment by wdhawkins** [comment]
At some point, we need to debug CBC. If we can boost the performance a tad and drastically reduce the memory usage, it might be the way of the future. I'm not sure why the memory usage is so high. I think that must be a bug or at least a bug in my understanding. It will be more challenging to get it to work well on GPUs though.

**Comment by andrsd** [comment]
> I'm not sure why the memory usage is so high.

I thought that was because one has to set `save_angular_fluxes` to true for it to work. This would allocate `n_nodes * n_groups * n_directions` (not only boundary nodes, but all mesh nodes) which might be a lot of RAM. At least I think this might be the "biggest offender"...
